version: "3"

services:
  app:
    build: .
    container_name: gokafka
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #   ZOOKEEPER_OPTS: "-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf"
    # volumes:
    #   - ./.docker/kafka/auth/zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      # KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092,PLAINTEXT://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Configure authentication on Kafka
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf

      # SASL configuration for Kafka broker
      KAFKA_SASL_JAAS_CONFIG: |
        KafkaServer {
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="admin"
          password="admin-secret";
        };
        Client {
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="admin"
          password="admin-secret";
        };

      # SASL configuration for inter-broker communication
      listener.name.sasl_plaintext.scram-sha-256.sasl.jaas.config: |
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="admin"
        password="admin-secret";
    # volumes:
    #   - ./.docker/kafka/server.properties:/etc/kafka/server.properties
    #   - ./.docker/kafka/auth/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    # command:
    #   - bash
    #   - -c
    #   - |
    #     echo "Creating users..."
    #     kafka-configs --bootstrap-server localhost:9092 --alter --add-config 'SCRAM-SHA-256=[iterations=4096,password=admin-secret]' --entity-type users --entity-name admin
    #     echo "Starting Kafka..."
    #     /etc/confluent/docker/run
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:6.0.1
  #   hostname: control-center
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "9021:9021"
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     CONTROL_CENTER_CONNECT_CLUSTER: http://app-connect:8083
  #     PORT: 9021
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"
